[versions]
kotlin              = "1.6.10"
ktlint              = "10.2.0"
minecraft           = "1.18.1"
fabric-loader       = "0.12.12"
fabric-kotlin       = "1.7.1+kotlin.1.6.10"
fabric-loom         = "0.10-SNAPSHOT"
fabric-api          = "0.45.0+1.18"

[libraries]
minecraft           = { module = "com.mojang:minecraft", version.ref = "minecraft"}
# yarn-mappings       = "net.fabricmc:yarn:1.18.1+build.12:v2"
fabric-loader       = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader"}
fabric-kotlin       = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-kotlin"}
fabric-api          = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api"}

[plugins]
fabric-loom         = { id = "fabric-loom", version.ref = "fabric-loom" }
kotlin              = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin"}
ktlint              = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint"}
